### ISSUE TITLE
Learning Resources: PSM

### ISSUE THREAD

**Issue by MrHinsh** [nkdAgility/NKDAgility.com#140]
```YAML
syllabus:
  - id: 1
    title: Theory & First Principles
    learningResources:
          - title: The New New Product Development Game
            link: https://hbr.org/1986/01/the-new-new-product-development-game
            duration: 20
            type: newspaper
            weight: 1
          - title: An Introduction to the Cynefin Model
            link: https://youtu.be/yjXRY0IbJw8
            duration: 5
            type: video
            weight: 1
          - title: A Leader’s Framework for Decision Making
            link: https://hbr.org/2007/11/a-leaders-framework-for-decision-making
            duration: 20
            type: newspaper
            weight: 1
```
