### ISSUE TITLE
Learning Resources: PAL-EBM

### ISSUE THREAD

**Issue by Eliane-I** [nkdAgility/NKDAgility.com#192]
Based on theexisting syllabus data format incorproate this into the PAL-EBM. Id like to split it into 4 parts rather than 2.

Session 1:
- Introductions (15m)
- Goals, Evidence, and Empiricism (100m)

Session 2:
- Goals: Understanding Why (100m)

Session 3:
- Evidence: Focusing on Value (100m)

Session 4:
- Empiricism: Inspect and Adapt with EBM (30m)
- Getting Started (100m)

I'll likely need to source assignments and learning resources separately. if you don't have a one use a placeholder.

```
syllabus:
  - id: 1
    title: Measure, Trust, Goals
    learningResources:
          - title: Empiricism, the act of making decisions based on what is
            link: https://kenschwaber.wordpress.com/2011/05/03/empiricism-the-act-of-making-decisions-based-on-what-is/
            duration: 
            type: 
            weight: 1
          - title: The Evidence-based Management Guide
            link: https://nkdagility.com/the-evidence-based-management-guide-measuring-value-to-enable-improvement-and-agility/
            duration: 
            type: 
            weight: 1
          - title: Unintended consequences
            link: https://youtu.be/a5G_mPCPpzk
            duration: 16
            type: video
            weight: 1 
          - title: Aligned Autonomy
            link: https://youtu.be/_qIh2sYXcQc
            duration: 2
            type: video
            weight: 1 
          - title: The Cobra Effect
            link: https://youtu.be/7Vta9KbAemY
            duration: 2
            type: video
            weight: 1 
          - title: Microsoft Stack Ranking
            link: https://youtu.be/RZZJca-X__k
            duration: 4
            type: video
            weight: 1 
  - id: 1
    title: KVA's, EBM, & Getting Started
    learningResources:
          - title: Speed, Efficiency, and Value: Using Empiricism to Achieve Business Agility
            link: https://www.infoq.com/articles/empiricism-business-agility/
            duration: 
            type: 
            weight: 1
          - title: Using Empiricism to Achieve Business Agility
            link: 
            duration: 
            type: 
            weight: 1
          - title: The Curse of the Change Control Mechanism
            link: https://www.infoq.com/articles/the-curse-of-the-change-control-mechanism/
            duration: 5
            type: 
            weight: 1 
   - id: 1
    title: CLOSING
```
